// Themes: to add a new one, append an object to this list.
//
//   id          unique string, stored in the save file
//   name        shown in the Themes panel
//   icon        emoji on the theme button
//   unlockedBy  optional prize id (see prizes.js); without it the theme is free
//   vars        CSS variables from :root in styles.css to override.
//               Anything left out keeps the Classic value.
const THEMES = [
  {
    id: 'classic',
    name: 'Classic',
    icon: '🪨',
    vars: {},
  },
  {
    id: 'sandstone',
    name: 'Sandstone',
    icon: '🏜️',
    unlockedBy: 'first-building',
    vars: {
      '--bg': '#fbf4e6',
      '--panel-bg': '#f1e4c8',
      '--border': '#dcc79d',
      '--card-bg': '#fffaf0',
      '--accent': '#b5762a',
      '--stone-light': '#f3dcae',
      '--stone-spot': '#a8763b',
      '--stone-top': '#e0b878',
      '--stone-middle': '#c99a55',
      '--stone-bottom': '#9c7038',
      '--stone-crack': 'rgb(92 58 20 / 55%)',
    },
  },
  {
    id: 'night',
    name: 'Night Quarry',
    icon: '🌙',
    unlockedBy: 'clicks-1000',
    vars: {
      '--bg': '#15181d',
      '--text': '#e8eaed',
      '--text-strong': '#dadce0',
      '--text-muted': '#9aa0a6',
      '--text-faint': '#6f757b',
      '--panel-bg': '#1d2127',
      '--card-bg': '#262b33',
      '--border': '#39404a',
      '--accent': '#8ab4f8',
      '--danger': '#f28b82',
    },
  },
  {
    id: 'emerald',
    name: 'Emerald',
    icon: '💚',
    unlockedBy: 'total-100k',
    vars: {
      '--bg': '#eef8f1',
      '--panel-bg': '#dcefe2',
      '--border': '#a9d3b6',
      '--card-bg': '#f8fdf9',
      '--accent': '#137a3f',
      '--stone-light': '#8ff0b5',
      '--stone-spot': '#0b5c2e',
      '--stone-top': '#34c46f',
      '--stone-middle': '#179150',
      '--stone-bottom': '#0c6135',
      '--stone-crack': 'rgb(4 44 22 / 60%)',
    },
  },
  {
    id: 'lava',
    name: 'Lava',
    icon: '🌋',
    unlockedBy: 'rate-1000',
    vars: {
      '--bg': '#1c0f0c',
      '--text': '#fbe9e4',
      '--text-strong': '#ffd2c2',
      '--text-muted': '#d49a88',
      '--text-faint': '#9c6b5e',
      '--panel-bg': '#261410',
      '--card-bg': '#331b15',
      '--border': '#5a2d22',
      '--accent': '#ff7a3d',
      '--danger': '#ff8a80',
      '--stone-light': '#ffb36b',
      '--stone-spot': '#ff4d1a',
      '--stone-top': '#4a3029',
      '--stone-middle': '#2e1c18',
      '--stone-bottom': '#170d0b',
      '--stone-crack': 'rgb(255 110 40 / 90%)',
      '--stone-ink': '#ffb36b',
    },
  },
  {
    id: 'gold',
    name: 'Golden Nugget',
    icon: '👑',
    unlockedBy: 'total-1b',
    vars: {
      '--bg': '#fffbea',
      '--panel-bg': '#fdf1c4',
      '--border': '#ecd27a',
      '--card-bg': '#fffef5',
      '--accent': '#b8860b',
      '--stone-light': '#fff4b0',
      '--stone-spot': '#a87a00',
      '--stone-top': '#ffd84d',
      '--stone-middle': '#e5b422',
      '--stone-bottom': '#b3860a',
      '--stone-crack': 'rgb(110 75 0 / 55%)',
    },
  },
];
